### ISSUE TITLE
Domains Page Re-Design

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#201]
- [x] Remove Help Link: Issue #198 
- [ ] Re-Design Token Balance on MainTopBar: Issue #194 
- [x] Extend Clickable Domains in Domains Table: Issue #193 
- [x] Restrict ADT to Stake in Application Container: Issue #178 
- [x] www. before each domain: Issue #176 
- [ ] Add the adToken Bounty Program Container
- [x] Add the count of total domains in each stage within the filter box

![image](https://user-images.githubusercontent.com/21111803/38572470-0b1b1b2c-3ca8-11e8-978d-38d377cd0aeb.png)
