### ISSUE TITLE
Nice-to-Haves

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#234]
- [ ] Modals in Domains Section (Issue #87)
- [ ] Make Columns in Dashboard Collapse-able (Issue #132)
- [ ] Add Hover-Over Highlights in Dashboard (Issue #131)
- [ ] Dark Theme adChain Registry (Issue #120)
- [ ] Governance Module Warnings (Issue #108)
- [ ] Olympia's Blockchain Transaction Tracker (Issue #88)
