### ISSUE TITLE
MainTopBar Edits

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryDapp#235]
# Problem
Users on 13" screens are having trouble seeing their ADT balance and don't realize there's an `Acquire ADT` button on the top-left if they don't have ADT. 

# Solution
Implement the items below to reformat the MainTopBar. 

### Time Zone
- [x] Remove `Time Zone`

### Wallet Address
- [x] Minimize the user's Wallet Address to 8 initial and the last 4 characters:
`0x7609E21921C7EFCF73a588833Bf7709889291781` to `0x7609E2...1781`
   - If this can't be done, 8 initial with the ... works.
- [x] Allow the user to click on their wallet address and send them to their etherscan (issue #226)
- [x] Add an underline and a finger when the user hovers over the address

### Ethereum Balance
- [x] Add a button that reads `BUY ETHEREUM` to the right of the ETH balance, with the link sending them to 
- [x] Have the button filled in with #424242 background and #fff text color
- [x] This button will always exist, even if they have ETH

### adToken Balance
- [x] Add a button that reads `BUY ETHEREUM` to the right of the ETH balance, with the link sending them to https://adchain.zendesk.com/hc/en-us/articles/360003417354
- [x] Have the button filled in with #3434CE background and #fff text color
- [x] This button will always exist, even if they have ADT

All in all, the MainTopBar should look like this: 
![image](https://user-images.githubusercontent.com/21111803/39494410-24d17c42-4d4b-11e8-8b50-b0367c415444.png)
